---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
  knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>",
    fig.path = "man/figures/README-",
    out.width = "100%"
)
```

# `{fioRa}`

<!-- badges: start -->
<!-- badges: end -->

## Installation

You can install the development version of `{fioRa}` like so:

```{r, eval = FALSE}
install.packages("devtools")
devtools::install_github("janlisec/fioRa")
```

## Run

You can launch the application as a Shiny-App by running:

```{r, eval = FALSE}
fioRa::run_app()
```

or use the exported function `predict` to work in R directly:

```{r, eval = FALSE}
fioRa::predict()
```

## About

You are reading the doc about version `r golem::pkg_version()` compiled on `r Sys.time() `.

Here are the tests results and package coverage:

```{r, error = TRUE}
devtools::check(quiet = TRUE)
```

```{r echo = FALSE}
unloadNamespace("fioRa")
```

```{r, error = TRUE}
covr::package_coverage()
```
